name: Build
on: [ pull_request, push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Unit tests
        run: bash ./gradlew test --stacktrace


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ktlint
        run: bash ./gradlew ktlintFormat --stacktrace